package com.suppercoder.java.formdesigner.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTemplate<M extends BaseTemplate<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setProcessId(java.lang.Integer processId) {
		set("processId", processId);
		return (M)this;
	}

	public java.lang.Integer getProcessId() {
		return get("processId");
	}

	public M setPageName(java.lang.String pageName) {
		set("pageName", pageName);
		return (M)this;
	}

	public java.lang.String getPageName() {
		return get("pageName");
	}

	public M setTemplate(java.lang.String template) {
		set("template", template);
		return (M)this;
	}

	public java.lang.String getTemplate() {
		return get("template");
	}

	public M setPageData(java.lang.String pageData) {
		set("pageData", pageData);
		return (M)this;
	}

	public java.lang.String getPageData() {
		return get("pageData");
	}

}
